# Generated by Django 2.2.24 on 2023-04-11 11:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20230406_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
