# Generated by Django 2.2.24 on 2023-04-12 10:56
from phonenumbers import parse, is_valid_number, format_number, PhoneNumberFormat
from django.db import migrations


def normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    country_code = 'RU'
    for flat in Flat.objects.iterator():
        phone_number = parse(flat.owners_phonenumber, country_code)
        if is_valid_number(phone_number):
            flat.owner_pure_phonenumber = format_number(phone_number, PhoneNumberFormat.E164)
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phonenumber'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumber)
    ]
