# Generated by Django 2.2.24 on 2023-04-17 07:11

from django.db import migrations


def create_relation(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.iterator():
        owner.flats.set(Flat.objects.filter(owner=owner.name))


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.iterator():
        owner.flats.clear()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0010_fill_in_the_owner_table'),
    ]

    operations = [
        migrations.RunPython(create_relation, reverse_code=move_backward)
    ]
