# Generated by Django 2.2.24 on 2023-04-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_mtm_relationship_Flat_and_Owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phonenumber',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
