# Generated by Django 2.2.24 on 2023-04-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_removed_the_Flat_model_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phonenumber',
            new_name='pure_phone_number',
        ),
    ]
